"""allow multiple services in the rule

Revision ID: 06d1b7e1e526
Revises: 5490024c4ad4
Create Date: 2026-04-22 22:49:13.431480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d1b7e1e526'
down_revision: Union[str, Sequence[str], None] = '5490024c4ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_rule_services',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['commission_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'service_id')
    )
    op.drop_index(op.f('ix_commission_rules_service_id'), table_name='commission_rules')
    op.drop_constraint(op.f('commission_rules_service_id_fkey'), 'commission_rules', type_='foreignkey')
    op.drop_column('commission_rules', 'service_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission_rules', sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('commission_rules_service_id_fkey'), 'commission_rules', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_commission_rules_service_id'), 'commission_rules', ['service_id'], unique=False)
    op.drop_table('commission_rule_services')
    # ### end Alembic commands ###
