"""add comission module

Revision ID: 08d3c3b099a7
Revises: 6be60b4f9ff5
Create Date: 2026-04-22 21:37:52.994096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d3c3b099a7'
down_revision: Union[str, Sequence[str], None] = '6be60b4f9ff5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('groomer', 'vet', 'salesperson', 'other', 'bather', name='employee_role'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
    op.create_table('commission_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('applies_to', sa.Enum('service', 'product', 'both', name='commission_applies_to'), nullable=False),
    sa.Column('commission_type', sa.Enum('percentage', 'fixed', name='commission_type'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_rules_employee_id'), 'commission_rules', ['employee_id'], unique=False)
    op.create_index(op.f('ix_commission_rules_service_id'), 'commission_rules', ['service_id'], unique=False)
    op.create_index(op.f('ix_commission_rules_tenant_id'), 'commission_rules', ['tenant_id'], unique=False)
    op.create_table('commission_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('sale_item_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('commission_type', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', name='commission_entry_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['commission_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_entries_employee_id'), 'commission_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_commission_entries_sale_id'), 'commission_entries', ['sale_id'], unique=False)
    op.create_index(op.f('ix_commission_entries_tenant_id'), 'commission_entries', ['tenant_id'], unique=False)
    op.add_column('appointment_items', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointment_items', 'employees', ['employee_id'], ['id'], ondelete='SET NULL')
    op.add_column('sale_items', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sale_items', 'employees', ['employee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale_items', type_='foreignkey')
    op.drop_column('sale_items', 'employee_id')
    op.drop_constraint(None, 'appointment_items', type_='foreignkey')
    op.drop_column('appointment_items', 'employee_id')
    op.drop_index(op.f('ix_commission_entries_tenant_id'), table_name='commission_entries')
    op.drop_index(op.f('ix_commission_entries_sale_id'), table_name='commission_entries')
    op.drop_index(op.f('ix_commission_entries_employee_id'), table_name='commission_entries')
    op.drop_table('commission_entries')
    op.drop_index(op.f('ix_commission_rules_tenant_id'), table_name='commission_rules')
    op.drop_index(op.f('ix_commission_rules_service_id'), table_name='commission_rules')
    op.drop_index(op.f('ix_commission_rules_employee_id'), table_name='commission_rules')
    op.drop_table('commission_rules')
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
