"""add more fields into pets table

Revision ID: 093c9d99d7f1
Revises: b35f6cd10846
Create Date: 2026-02-10 20:11:24.197402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093c9d99d7f1'
down_revision: Union[str, Sequence[str], None] = 'b35f6cd10846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('size', sa.String(length=5), nullable=True))
    op.add_column('pets', sa.Column('coat_type', sa.String(length=30), nullable=True))
    op.add_column('pets', sa.Column('coat_color', sa.String(length=50), nullable=True))
    op.add_column('pets', sa.Column('age_unit', sa.String(length=10), nullable=True))
    op.add_column('pets', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('pets', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('pets', 'gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('pets', 'ageUnit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('ageUnit', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.alter_column('pets', 'gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('pets', 'notes')
    op.drop_column('pets', 'birth_date')
    op.drop_column('pets', 'age_unit')
    op.drop_column('pets', 'coat_color')
    op.drop_column('pets', 'coat_type')
    op.drop_column('pets', 'size')
    # ### end Alembic commands ###
