"""add soft delete in users table

Revision ID: 0a508451d209
Revises: aa1ef78f4b52
Create Date: 2026-03-16 21:51:40.600629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a508451d209'
down_revision: Union[str, Sequence[str], None] = 'aa1ef78f4b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_users', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_users', 'active')
    # ### end Alembic commands ###
