"""multi_pet_packages

Revision ID: 19ac09d4cedc
Revises: be602fc234f9
Create Date: 2026-07-18 21:14:45.517282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ac09d4cedc'
down_revision: Union[str, Sequence[str], None] = 'be602fc234f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_package_pets',
    sa.Column('client_package_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_package_id'], ['client_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_package_id', 'pet_id')
    )
    
    # Data migration: copy existing pet_id to the new association table
    op.execute(
        "INSERT INTO client_package_pets (client_package_id, pet_id) "
        "SELECT id, pet_id FROM client_packages WHERE pet_id IS NOT NULL"
    )

    op.drop_index(op.f('ix_client_packages_pet_id'), table_name='client_packages')
    op.drop_constraint(op.f('client_packages_pet_id_fkey'), 'client_packages', type_='foreignkey')
    op.drop_column('client_packages', 'pet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_packages', sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=True))
    
    # Data migration: backfill pet_id from the association table (taking the first pet if multiple exist)
    op.execute(
        "UPDATE client_packages SET pet_id = subquery.pet_id "
        "FROM (SELECT client_package_id, MIN(pet_id) as pet_id FROM client_package_pets GROUP BY client_package_id) AS subquery "
        "WHERE client_packages.id = subquery.client_package_id"
    )

    # Now make it NOT NULL
    op.alter_column('client_packages', 'pet_id', nullable=False)

    op.create_foreign_key(op.f('client_packages_pet_id_fkey'), 'client_packages', 'pets', ['pet_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_client_packages_pet_id'), 'client_packages', ['pet_id'], unique=False)
    op.drop_table('client_package_pets')
    # ### end Alembic commands ###
