"""add stripe

Revision ID: 246ad11a78d5
Revises: 64f897ca1a8f
Create Date: 2026-04-01 23:02:47.667704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246ad11a78d5'
down_revision: Union[str, Sequence[str], None] = '64f897ca1a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('stripe_price_id', sa.String(length=100), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'subscriptions', ['stripe_subscription_id'])
    op.add_column('tenants', sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'tenants', ['stripe_customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='unique')
    op.drop_column('tenants', 'stripe_customer_id')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.drop_column('plans', 'stripe_price_id')
    # ### end Alembic commands ###
