"""add new fields in products table

Revision ID: 26613739f2b1
Revises: d539fca7dfae
Create Date: 2026-04-12 17:34:27.610467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26613739f2b1'
down_revision: Union[str, Sequence[str], None] = 'd539fca7dfae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('ncm', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('cest', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('cfop', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('csosn', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('cst_pis', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('cst_cofins', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'supplier_id')
    op.drop_column('products', 'cst_cofins')
    op.drop_column('products', 'cst_pis')
    op.drop_column('products', 'csosn')
    op.drop_column('products', 'cfop')
    op.drop_column('products', 'cest')
    op.drop_column('products', 'ncm')
    op.drop_column('products', 'barcode')
    # ### end Alembic commands ###
