"""add_card_details_to_subscription_charges

Revision ID: 2e1b4c281195
Revises: d50ef8a6035f
Create Date: 2026-06-11 17:19:02.659255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1b4c281195'
down_revision: Union[str, Sequence[str], None] = 'd50ef8a6035f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_charges', sa.Column('card_brand', sa.String(length=20), nullable=True))
    op.add_column('subscription_charges', sa.Column('card_last_four', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_charges', 'card_last_four')
    op.drop_column('subscription_charges', 'card_brand')
    # ### end Alembic commands ###
