"""add warning for comission

Revision ID: 2e93ca3f1d5b
Revises: d5ac1c66a017
Create Date: 2026-05-20 20:38:07.075703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e93ca3f1d5b'
down_revision: Union[str, Sequence[str], None] = 'd5ac1c66a017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission_entries', sa.Column('appointment_item_id', sa.Integer(), nullable=True))
    op.alter_column('commission_entries', 'sale_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('commission_entries', 'sale_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'commission_entries', 'appointment_items', ['appointment_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commission_entries', type_='foreignkey')
    op.alter_column('commission_entries', 'sale_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('commission_entries', 'sale_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('commission_entries', 'appointment_item_id')
    # ### end Alembic commands ###
