"""Add index to appointment_id and pet_id in appointment_items

Revision ID: 3701fbb9ee97
Revises: 16a400f91146
Create Date: 2026-08-12 23:29:13.163313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3701fbb9ee97'
down_revision: Union[str, Sequence[str], None] = '16a400f91146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_jobs_tenant_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.create_index(op.f('ix_appointment_items_appointment_id'), 'appointment_items', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_appointment_items_pet_id'), 'appointment_items', ['pet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_items_pet_id'), table_name='appointment_items')
    op.drop_index(op.f('ix_appointment_items_appointment_id'), table_name='appointment_items')
    op.create_table('import_jobs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('imported', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('errors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('import_jobs_pkey'))
    )
    op.create_index(op.f('ix_import_jobs_tenant_id'), 'import_jobs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
