"""refactor service tables

Revision ID: 37d7ef1349d5
Revises: 762336f20bc5
Create Date: 2026-02-12 20:42:29.156689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37d7ef1349d5'
down_revision: Union[str, Sequence[str], None] = '762336f20bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_pricings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('species', sa.Enum('CANINO', 'FELINO', 'EXOTICOS', name='petspecies'), nullable=False),
    sa.Column('size', sa.Enum('PP', 'P', 'M', 'G', 'GG', name='petsize'), nullable=True),
    sa.Column('coat_type', sa.String(length=50), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'service_id', 'species', 'size', 'coat_type', name='uq_service_pricing_rule')
    )
    op.create_index(op.f('ix_service_pricings_service_id'), 'service_pricings', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_pricings_tenant_id'), 'service_pricings', ['tenant_id'], unique=False)
    op.alter_column('services', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.drop_column('services', 'price_cents')
    op.drop_column('services', 'duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('price_cents', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('services', 'name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_service_pricings_tenant_id'), table_name='service_pricings')
    op.drop_index(op.f('ix_service_pricings_service_id'), table_name='service_pricings')
    op.drop_table('service_pricings')
    # ### end Alembic commands ###
