"""add_schedule_token_to_employee

Revision ID: 3d516156d9ac
Revises: 2e1b4c281195
Create Date: 2026-06-12 22:33:53.396514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d516156d9ac'
down_revision: Union[str, Sequence[str], None] = '2e1b4c281195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('schedule_token', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'employees', ['schedule_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'schedule_token')
    # ### end Alembic commands ###
