"""make species field optional

Revision ID: 4cd7d7086dd4
Revises: 37d7ef1349d5
Create Date: 2026-02-12 20:51:59.153934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cd7d7086dd4'
down_revision: Union[str, Sequence[str], None] = '37d7ef1349d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_pricings', 'species',
               existing_type=postgresql.ENUM('CANINO', 'FELINO', 'EXOTICOS', name='petspecies'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_pricings', 'species',
               existing_type=postgresql.ENUM('CANINO', 'FELINO', 'EXOTICOS', name='petspecies'),
               nullable=False)
    # ### end Alembic commands ###
