"""link stock table

Revision ID: 4ebc20611146
Revises: 12e2ebd2a417
Create Date: 2026-03-15 17:26:45.451725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ebc20611146'
down_revision: Union[str, Sequence[str], None] = '12e2ebd2a417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('appointment_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sales_appointment_id'), 'sales', ['appointment_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'appointments', ['appointment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_appointment_id'), table_name='sales')
    op.drop_column('sales', 'appointment_id')
    # ### end Alembic commands ###
