"""remove priority field

Revision ID: 5490024c4ad4
Revises: 08d3c3b099a7
Create Date: 2026-04-22 22:27:58.895140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5490024c4ad4'
down_revision: Union[str, Sequence[str], None] = '08d3c3b099a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commission_rules', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission_rules', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
