"""add tenant document

Revision ID: 5d0e6043149b
Revises: e5bf4ec28061
Create Date: 2026-04-04 18:28:00.108984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d0e6043149b'
down_revision: Union[str, Sequence[str], None] = 'e5bf4ec28061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('document', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'document')
    # ### end Alembic commands ###
