"""add_tenant_id_to_pet_photos

Revision ID: 627c40a30c3c
Revises: d2b4fa5be124
Create Date: 2026-06-28 01:06:36.234028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627c40a30c3c'
down_revision: Union[str, Sequence[str], None] = 'd2b4fa5be124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Adiciona a coluna permitindo valores temporariamente nulos
    op.add_column('pet_photos', sa.Column('tenant_id', sa.Integer(), nullable=True))
    
    # 2. Preenche a coluna tenant_id com base na tabela pets
    op.execute(
        "UPDATE pet_photos SET tenant_id = (SELECT tenant_id FROM pets WHERE pets.id = pet_photos.pet_id)"
    )
    
    # 3. Altera a coluna para NOT NULL
    op.alter_column('pet_photos', 'tenant_id', nullable=False)
    
    # 4. Cria o índice e a chave estrangeira
    op.create_index(op.f('ix_pet_photos_tenant_id'), 'pet_photos', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'pet_photos', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pet_photos', type_='foreignkey')
    op.drop_index(op.f('ix_pet_photos_tenant_id'), table_name='pet_photos')
    op.drop_column('pet_photos', 'tenant_id')
    # ### end Alembic commands ###
