"""add appointment index

Revision ID: 64f897ca1a8f
Revises: c6b7504229a0
Create Date: 2026-03-28 21:16:25.898702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f897ca1a8f'
down_revision: Union[str, Sequence[str], None] = 'c6b7504229a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_appointments_tenant_scheduled', 'appointments', ['tenant_id', 'scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_appointments_tenant_scheduled', table_name='appointments')
    # ### end Alembic commands ###
