"""allow multiple employee in the same appointment

Revision ID: 676b804b2b05
Revises: 06d1b7e1e526
Create Date: 2026-04-25 18:25:42.384532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676b804b2b05'
down_revision: Union[str, Sequence[str], None] = '06d1b7e1e526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_item_services', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointment_item_services', 'employees', ['employee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment_item_services', type_='foreignkey')
    op.drop_column('appointment_item_services', 'employee_id')
    # ### end Alembic commands ###
