"""add expiration to packages

Revision ID: 6be60b4f9ff5
Revises: 26613739f2b1
Create Date: 2026-04-21 15:18:44.910896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be60b4f9ff5'
down_revision: Union[str, Sequence[str], None] = '26613739f2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_packages', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('packages', sa.Column('validity_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('packages', 'validity_days')
    op.drop_column('client_packages', 'expires_at')
    # ### end Alembic commands ###
