"""delete cascade pets

Revision ID: 716c17574f83
Revises: 91cd22e67e72
Create Date: 2026-03-07 21:01:13.404913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '716c17574f83'
down_revision: Union[str, Sequence[str], None] = '91cd22e67e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointment_items_pet_id_fkey'), 'appointment_items', type_='foreignkey')
    op.create_foreign_key(None, 'appointment_items', 'pets', ['pet_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('appointments_client_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_client_id_fkey'), 'appointments', 'clients', ['client_id'], ['id'])
    op.drop_constraint(None, 'appointment_items', type_='foreignkey')
    op.create_foreign_key(op.f('appointment_items_pet_id_fkey'), 'appointment_items', 'pets', ['pet_id'], ['id'])
    # ### end Alembic commands ###
