"""add_unit_to_product

Revision ID: 745b7f4ccd5b
Revises: a7312c52599a
Create Date: 2026-06-05 22:12:09.797665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745b7f4ccd5b'
down_revision: Union[str, Sequence[str], None] = 'a7312c52599a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unit', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'unit')
    # ### end Alembic commands ###
