"""add_roles_to_employee_role

Revision ID: 7baf5104272c
Revises: 9053939fa9f8
Create Date: 2026-06-05 22:25:02.280066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7baf5104272c'
down_revision: Union[str, Sequence[str], None] = '9053939fa9f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("COMMIT")
    op.execute("ALTER TYPE employee_role ADD VALUE 'receptionist'")
    op.execute("ALTER TYPE employee_role ADD VALUE 'driver'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
