"""refactor appointment tables

Revision ID: 821bac7c2a34
Revises: 0e59c79e96b3
Create Date: 2026-02-14 20:38:37.751084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821bac7c2a34'
down_revision: Union[str, Sequence[str], None] = '0e59c79e96b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment_item_services',
    sa.Column('appointment_item_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_item_id'], ['appointment_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_item_id', 'service_id')
    )
    op.drop_table('appointment_services')
    op.drop_constraint(op.f('appointments_pet_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'pet_id')
    op.drop_constraint(op.f('uq_service_variant'), 'services', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_service_variant'), 'services', ['tenant_id', 'name', 'species', 'size', 'coat_type'], postgresql_nulls_not_distinct=True)
    op.add_column('appointments', sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('appointments_pet_id_fkey'), 'appointments', 'pets', ['pet_id'], ['id'])
    op.create_table('appointment_services',
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('appointment_services_appointment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('appointment_services_service_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id', 'service_id', name=op.f('appointment_services_pkey'))
    )
    op.drop_table('appointment_item_services')
    op.drop_table('appointment_items')
    # ### end Alembic commands ###
