"""add_catalog_performance_indexes

Revision ID: 84e3197ef8fe
Revises: f10119dba27b
Create Date: 2026-06-18 22:42:23.169820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84e3197ef8fe'
down_revision: Union[str, Sequence[str], None] = 'f10119dba27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_clients_tenant_name', 'clients', ['tenant_id', 'name'], unique=False)
    op.create_index(op.f('ix_package_items_package_id'), 'package_items', ['package_id'], unique=False)
    op.create_index(op.f('ix_package_items_product_id'), 'package_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_package_items_service_id'), 'package_items', ['service_id'], unique=False)
    op.create_index('ix_packages_tenant_name', 'packages', ['tenant_id', 'name'], unique=False)
    op.create_index('ix_products_tenant_name', 'products', ['tenant_id', 'name'], unique=False)
    op.create_index('ix_services_tenant_name', 'services', ['tenant_id', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_services_tenant_name', table_name='services')
    op.drop_index('ix_products_tenant_name', table_name='products')
    op.drop_index('ix_packages_tenant_name', table_name='packages')
    op.drop_index(op.f('ix_package_items_service_id'), table_name='package_items')
    op.drop_index(op.f('ix_package_items_product_id'), table_name='package_items')
    op.drop_index(op.f('ix_package_items_package_id'), table_name='package_items')
    op.drop_index('ix_clients_tenant_name', table_name='clients')
    # ### end Alembic commands ###
