"""add cpf/cnpj ad birth date

Revision ID: 856f0008c733
Revises: a19489dbc11b
Create Date: 2026-02-08 21:54:22.869862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856f0008c733'
down_revision: Union[str, Sequence[str], None] = 'a19489dbc11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('document_type', sa.String(length=10), nullable=True))
    op.add_column('clients', sa.Column('document', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('birth_date', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'birth_date')
    op.drop_column('clients', 'document')
    op.drop_column('clients', 'document_type')
    # ### end Alembic commands ###
