"""add_contact_fields_to_supplier

Revision ID: 9053939fa9f8
Revises: 745b7f4ccd5b
Create Date: 2026-06-05 22:20:04.365925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9053939fa9f8'
down_revision: Union[str, Sequence[str], None] = '745b7f4ccd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('phone_1', sa.String(length=20), nullable=True))
    op.add_column('suppliers', sa.Column('phone_2', sa.String(length=20), nullable=True))
    op.add_column('suppliers', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'email')
    op.drop_column('suppliers', 'phone_2')
    op.drop_column('suppliers', 'phone_1')
    # ### end Alembic commands ###
