"""add onboarding_step to tenants table

Revision ID: 91cd22e67e72
Revises: 421ab104c8f6
Create Date: 2026-02-21 19:16:39.745427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91cd22e67e72'
down_revision: Union[str, Sequence[str], None] = '421ab104c8f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('onboarding_step', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'onboarding_step')
    # ### end Alembic commands ###
