"""add phone to tenant

Revision ID: 94717b160ede
Revises: 6f61677a9e1b
Create Date: 2026-02-02 21:34:16.754563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94717b160ede'
down_revision: Union[str, Sequence[str], None] = '6f61677a9e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('tenants', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'created_at')
    op.drop_column('tenants', 'phone')
    # ### end Alembic commands ###
