"""add_tenant_cards_table

Revision ID: 9a50a75ae447
Revises: 0efb088553b0
Create Date: 2026-06-07 14:52:41.846897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a50a75ae447'
down_revision: Union[str, Sequence[str], None] = '0efb088553b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('tenant_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pagarme_card_id', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_cards_pagarme_card_id'), 'tenant_cards', ['pagarme_card_id'], unique=False)
    op.create_index(op.f('ix_tenant_cards_tenant_id'), 'tenant_cards', ['tenant_id'], unique=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_cards_tenant_id'), table_name='tenant_cards')
    op.drop_index(op.f('ix_tenant_cards_pagarme_card_id'), table_name='tenant_cards')
    op.drop_table('tenant_cards')
    # ### end Alembic commands ###
