"""add address fields in clinets table

Revision ID: a19489dbc11b
Revises: 94717b160ede
Create Date: 2026-02-08 12:15:39.285191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a19489dbc11b'
down_revision: Union[str, Sequence[str], None] = '94717b160ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone_secondary_name', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('phone_secondary', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('phone_tertiary_name', sa.String(length=50), nullable=True))
    op.add_column('clients', sa.Column('phone_tertiary', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('cep', sa.String(length=10), nullable=True))
    op.add_column('clients', sa.Column('street', sa.String(length=150), nullable=True))
    op.add_column('clients', sa.Column('number', sa.String(length=20), nullable=True))
    op.add_column('clients', sa.Column('complement', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('neighborhood', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('state', sa.String(length=2), nullable=True))
    op.add_column('clients', sa.Column('instagram', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('facebook', sa.String(length=255), nullable=True))
    op.add_column('clients', sa.Column('x', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'x')
    op.drop_column('clients', 'facebook')
    op.drop_column('clients', 'instagram')
    op.drop_column('clients', 'state')
    op.drop_column('clients', 'city')
    op.drop_column('clients', 'neighborhood')
    op.drop_column('clients', 'complement')
    op.drop_column('clients', 'number')
    op.drop_column('clients', 'street')
    op.drop_column('clients', 'cep')
    op.drop_column('clients', 'phone_tertiary')
    op.drop_column('clients', 'phone_tertiary_name')
    op.drop_column('clients', 'phone_secondary')
    op.drop_column('clients', 'phone_secondary_name')
    # ### end Alembic commands ###
