"""add_is_neutered_to_pet

Revision ID: a7312c52599a
Revises: 84f259f23dfd
Create Date: 2026-06-05 22:04:01.766420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7312c52599a'
down_revision: Union[str, Sequence[str], None] = '84f259f23dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('is_neutered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'is_neutered')
    # ### end Alembic commands ###
