"""add gender field

Revision ID: aab88f703906
Revises: 805e9653767b
Create Date: 2026-01-22 19:57:00.844450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab88f703906'
down_revision: Union[str, Sequence[str], None] = '805e9653767b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('gender', sa.String(length=10), nullable=False))
    op.add_column('pets', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_pets_created_at'), 'pets', ['created_at'], unique=False)
    op.create_index(op.f('ix_pets_gender'), 'pets', ['gender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pets_gender'), table_name='pets')
    op.drop_index(op.f('ix_pets_created_at'), table_name='pets')
    op.drop_column('pets', 'created_at')
    op.drop_column('pets', 'gender')
    # ### end Alembic commands ###
