"""add unique index with coalesce for services

Revision ID: bc816ebb0030
Revises: d07c5835e0b4
Create Date: 2026-02-13 21:27:26.049863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc816ebb0030'
down_revision: Union[str, Sequence[str], None] = 'd07c5835e0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_service_variant'), 'services', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_service_variant'), 'services', ['tenant_id', 'name', 'species', 'size', 'coat_type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
