"""refactor service tables

Revision ID: c2aee5410cda
Revises: f9364ca63dc5
Create Date: 2026-02-13 21:09:55.620250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2aee5410cda'
down_revision: Union[str, Sequence[str], None] = 'f9364ca63dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_pricings_service_id'), table_name='service_pricings')
    op.drop_index(op.f('ix_service_pricings_tenant_id'), table_name='service_pricings')
    op.drop_table('service_pricings')
    op.add_column('services', sa.Column('species', sa.Enum('CANINO', 'FELINO', 'EXOTICOS', name='petspecies'), nullable=True))
    op.add_column('services', sa.Column('size', sa.Enum('PP', 'P', 'M', 'G', 'GG', name='petsize'), nullable=True))
    op.add_column('services', sa.Column('coat_type', sa.String(length=50), nullable=True))
    op.add_column('services', sa.Column('price_cents', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'duration_minutes')
    op.drop_column('services', 'price_cents')
    op.drop_column('services', 'coat_type')
    op.drop_column('services', 'size')
    op.drop_column('services', 'species')
    op.create_table('service_pricings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('species', postgresql.ENUM('CANINO', 'FELINO', 'EXOTICOS', name='petspecies'), autoincrement=False, nullable=True),
    sa.Column('size', postgresql.ENUM('PP', 'P', 'M', 'G', 'GG', name='petsize'), autoincrement=False, nullable=True),
    sa.Column('coat_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('price_cents', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('service_pricings_service_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('service_pricings_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('service_pricings_pkey')),
    sa.UniqueConstraint('tenant_id', 'service_id', 'species', 'size', 'coat_type', name=op.f('uq_service_pricing_rule'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_service_pricings_tenant_id'), 'service_pricings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_service_pricings_service_id'), 'service_pricings', ['service_id'], unique=False)
    # ### end Alembic commands ###
