"""create_whatsapp_templates

Revision ID: c61e18382c9e
Revises: e84e4d08c30f
Create Date: 2026-06-15 17:53:33.798624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61e18382c9e'
down_revision: Union[str, Sequence[str], None] = 'e84e4d08c30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('message_template', sa.String(length=1000), nullable=False),
    sa.Column('buttons', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_templates_tenant_id'), 'whatsapp_templates', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_trigger_type'), 'whatsapp_templates', ['trigger_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_templates_trigger_type'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_tenant_id'), table_name='whatsapp_templates')
    op.drop_table('whatsapp_templates')
    # ### end Alembic commands ###
