"""fix coverage package

Revision ID: c6b7504229a0
Revises: e00a0e688ac9
Create Date: 2026-03-22 22:52:52.437089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b7504229a0'
down_revision: Union[str, Sequence[str], None] = 'e00a0e688ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_package_coverages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_item_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('client_package_credit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_item_id'], ['appointment_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_package_credit_id'], ['client_package_credits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_package_coverages_appointment_item_id'), 'appointment_package_coverages', ['appointment_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_package_coverages_appointment_item_id'), table_name='appointment_package_coverages')
    op.drop_table('appointment_package_coverages')
    # ### end Alembic commands ###
