"""add_cash_register_module

Revision ID: c9a79b8435e0
Revises: fb1c2d3e4f5a
Create Date: 2026-08-29 21:50:27.237977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9a79b8435e0'
down_revision: Union[str, Sequence[str], None] = 'fb1c2d3e4f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_registers_tenant_id'), 'cash_registers', ['tenant_id'], unique=False)
    op.create_table('cash_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('cash_register_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('opened_by_user_id', sa.Integer(), nullable=True),
    sa.Column('initial_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('expected_closing_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_closing_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('difference_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('closing_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cash_register_id'], ['cash_registers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['closed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_sessions_cash_register_id'), 'cash_sessions', ['cash_register_id'], unique=False)
    op.create_index(op.f('ix_cash_sessions_closed_by_user_id'), 'cash_sessions', ['closed_by_user_id'], unique=False)
    op.create_index(op.f('ix_cash_sessions_opened_at'), 'cash_sessions', ['opened_at'], unique=False)
    op.create_index(op.f('ix_cash_sessions_opened_by_user_id'), 'cash_sessions', ['opened_by_user_id'], unique=False)
    op.create_index(op.f('ix_cash_sessions_status'), 'cash_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_cash_sessions_tenant_id'), 'cash_sessions', ['tenant_id'], unique=False)
    op.create_table('cash_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('destination_or_origin', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['cash_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_movements_created_at'), 'cash_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_cash_movements_sale_id'), 'cash_movements', ['sale_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_session_id'), 'cash_movements', ['session_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_tenant_id'), 'cash_movements', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_type'), 'cash_movements', ['type'], unique=False)
    op.create_index(op.f('ix_cash_movements_user_id'), 'cash_movements', ['user_id'], unique=False)
    op.add_column('sales', sa.Column('cash_session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sales_cash_session_id'), 'sales', ['cash_session_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'cash_sessions', ['cash_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_cash_session_id'), table_name='sales')
    op.drop_column('sales', 'cash_session_id')
    op.drop_index(op.f('ix_cash_movements_user_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_type'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_tenant_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_session_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_sale_id'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_created_at'), table_name='cash_movements')
    op.drop_table('cash_movements')
    op.drop_index(op.f('ix_cash_sessions_tenant_id'), table_name='cash_sessions')
    op.drop_index(op.f('ix_cash_sessions_status'), table_name='cash_sessions')
    op.drop_index(op.f('ix_cash_sessions_opened_by_user_id'), table_name='cash_sessions')
    op.drop_index(op.f('ix_cash_sessions_opened_at'), table_name='cash_sessions')
    op.drop_index(op.f('ix_cash_sessions_closed_by_user_id'), table_name='cash_sessions')
    op.drop_index(op.f('ix_cash_sessions_cash_register_id'), table_name='cash_sessions')
    op.drop_table('cash_sessions')
    op.drop_index(op.f('ix_cash_registers_tenant_id'), table_name='cash_registers')
    op.drop_table('cash_registers')
    # ### end Alembic commands ###
