"""add flag for unpaid package

Revision ID: d5ac1c66a017
Revises: dd638def9261
Create Date: 2026-05-20 19:26:21.365444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ac1c66a017'
down_revision: Union[str, Sequence[str], None] = 'dd638def9261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_packages', sa.Column('is_paid', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_packages', 'is_paid')
    # ### end Alembic commands ###
