"""add notes fields into appointment table

Revision ID: d8e5581b2184
Revises: a5d50e9be28b
Create Date: 2026-01-25 20:33:43.380198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e5581b2184'
down_revision: Union[str, Sequence[str], None] = 'a5d50e9be28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('notes', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'notes')
    # ### end Alembic commands ###
