"""add waiting list table

Revision ID: da4da459672d
Revises: de0c978145cb
Create Date: 2026-06-02 14:53:27.291901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4da459672d'
down_revision: Union[str, Sequence[str], None] = 'de0c978145cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiting_list_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('preferred_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_period', sa.Enum('ANY', 'MORNING', 'AFTERNOON', 'EVENING', name='waiting_list_period'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'CANCELED', name='waiting_list_status'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiting_list_entries_status'), 'waiting_list_entries', ['status'], unique=False)
    op.create_index(op.f('ix_waiting_list_entries_tenant_id'), 'waiting_list_entries', ['tenant_id'], unique=False)
    op.create_table('waiting_list_services',
    sa.Column('waiting_list_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waiting_list_id'], ['waiting_list_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('waiting_list_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waiting_list_services')
    op.drop_index(op.f('ix_waiting_list_entries_tenant_id'), table_name='waiting_list_entries')
    op.drop_index(op.f('ix_waiting_list_entries_status'), table_name='waiting_list_entries')
    op.drop_table('waiting_list_entries')
    # ### end Alembic commands ###
