"""add client packages table

Revision ID: e00a0e688ac9
Revises: 0a508451d209
Create Date: 2026-03-22 22:39:09.331480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e00a0e688ac9'
down_revision: Union[str, Sequence[str], None] = '0a508451d209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('package_name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_packages_client_id'), 'client_packages', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_packages_pet_id'), 'client_packages', ['pet_id'], unique=False)
    op.create_index(op.f('ix_client_packages_tenant_id'), 'client_packages', ['tenant_id'], unique=False)
    op.create_table('client_package_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_package_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=150), nullable=False),
    sa.Column('total_qty', sa.Integer(), nullable=False),
    sa.Column('used_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_package_id'], ['client_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_package_credits_client_package_id'), 'client_package_credits', ['client_package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_package_credits_client_package_id'), table_name='client_package_credits')
    op.drop_table('client_package_credits')
    op.drop_index(op.f('ix_client_packages_tenant_id'), table_name='client_packages')
    op.drop_index(op.f('ix_client_packages_pet_id'), table_name='client_packages')
    op.drop_index(op.f('ix_client_packages_client_id'), table_name='client_packages')
    op.drop_table('client_packages')
    # ### end Alembic commands ###
