"""add ageUnit

Revision ID: e075625113ed
Revises: aab88f703906
Create Date: 2026-01-22 20:10:18.426836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e075625113ed'
down_revision: Union[str, Sequence[str], None] = 'aab88f703906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('ageUnit', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'ageUnit')
    # ### end Alembic commands ###
