"""pagarme integration

Revision ID: e5bf4ec28061
Revises: f68cbf81c6a7
Create Date: 2026-04-03 13:23:14.264469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5bf4ec28061'
down_revision: Union[str, Sequence[str], None] = 'f68cbf81c6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('pagarme_plan_id', sa.String(length=100), nullable=True))
    op.drop_column('plans', 'stripe_price_id')
    op.add_column('subscriptions', sa.Column('pagarme_subscription_id', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('subscriptions_stripe_subscription_id_key'), 'subscriptions', type_='unique')
    op.create_unique_constraint(None, 'subscriptions', ['pagarme_subscription_id'])
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.add_column('tenants', sa.Column('pagarme_customer_id', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('tenants_stripe_customer_id_key'), 'tenants', type_='unique')
    op.create_unique_constraint(None, 'tenants', ['pagarme_customer_id'])
    op.drop_column('tenants', 'stripe_customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('stripe_customer_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tenants', type_='unique')
    op.create_unique_constraint(op.f('tenants_stripe_customer_id_key'), 'tenants', ['stripe_customer_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('tenants', 'pagarme_customer_id')
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.create_unique_constraint(op.f('subscriptions_stripe_subscription_id_key'), 'subscriptions', ['stripe_subscription_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('subscriptions', 'pagarme_subscription_id')
    op.add_column('plans', sa.Column('stripe_price_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('plans', 'pagarme_plan_id')
    # ### end Alembic commands ###
