"""add_is_deceased_to_pets

Revision ID: ec5e7c15f31e
Revises: 627c40a30c3c
Create Date: 2026-07-05 21:21:32.004864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec5e7c15f31e'
down_revision: Union[str, Sequence[str], None] = '627c40a30c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('is_deceased', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'is_deceased')
    # ### end Alembic commands ###
