"""add is_internal_use to products

Revision ID: ee31ca0e2e6a
Revises: f90b8dc064d1
Create Date: 2026-07-19 13:50:05.231540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee31ca0e2e6a'
down_revision: Union[str, Sequence[str], None] = 'f90b8dc064d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('products', sa.Column('is_internal_use', sa.Boolean(), server_default=sa.text('false'), nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_internal_use')
    # ### end Alembic commands ###
