"""add_max_simultaneous_appointments_to_tenant

Revision ID: f10119dba27b
Revises: c61e18382c9e
Create Date: 2026-06-15 22:01:37.328520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10119dba27b'
down_revision: Union[str, Sequence[str], None] = 'c61e18382c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('max_simultaneous_appointments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'max_simultaneous_appointments')
    # ### end Alembic commands ###
