"""add tenant feature flags

Revision ID: f37b33527010
Revises: 05b316f699fc
Create Date: 2026-06-24 23:37:04.680757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37b33527010'
down_revision: Union[str, Sequence[str], None] = '05b316f699fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('feature_flags', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'feature_flags')
    # ### end Alembic commands ###
