"""add_user_id_to_client_package_usage

Revision ID: f727dbd0786e
Revises: ec5e7c15f31e
Create Date: 2026-07-05 21:42:03.757818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f727dbd0786e'
down_revision: Union[str, Sequence[str], None] = 'ec5e7c15f31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_package_usages', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_package_usages', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_package_usages', type_='foreignkey')
    op.drop_column('client_package_usages', 'user_id')
    # ### end Alembic commands ###
