"""Add recurrence_id

Revision ID: f90b8dc064d1
Revises: 19ac09d4cedc
Create Date: 2026-07-19 12:11:38.211276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f90b8dc064d1'
down_revision: Union[str, Sequence[str], None] = '19ac09d4cedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('recurrence_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_appointments_recurrence_id'), 'appointments', ['recurrence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_recurrence_id'), table_name='appointments')
    op.drop_column('appointments', 'recurrence_id')
    # ### end Alembic commands ###
