"""add duration field

Revision ID: f9364ca63dc5
Revises: 4cd7d7086dd4
Create Date: 2026-02-12 20:56:05.557525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9364ca63dc5'
down_revision: Union[str, Sequence[str], None] = '4cd7d7086dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_pricings', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_pricings', 'duration_minutes')
    # ### end Alembic commands ###
